CREATE TABLE [dbo].[Detail_Employee](
	[iEmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[vEmployeeName] [varchar](100) NULL,
	[vEmployeeFunction] [varchar](50) NULL,
	[cEmployeeStatus] [char](10) NULL,
	[vEmail] [varchar](200) NULL,
	[vManagerID] [varchar](50) NULL,
	[dHireDate] [datetime] NULL,
	[vNotes] [varchar](200) NULL,
	[bAccessFromAnywhere] [bit] NOT NULL,
	[iSourceID] [int] NULL,
	[vEmployeePhone] [varchar](50) NULL,
	[vEmployeeMobile] [varchar](50) NULL,
	[vEmployeeFax] [varchar](50) NULL,
	[vAlternateContactEmail] [varchar](100) NULL,
	[bCopyeMailsToAltContact] [bit] NOT NULL,
	[bCopyJobeMailsToSourceAltContact] [bit] NOT NULL,
	[bIsLandingPage] [bit] NOT NULL,
	[iFacilityID] [int] NOT NULL,
	[bIsPrimaryGM] [bit] NULL,
	[iWebUserID] [int] NOT NULL,
	[bRequirePasswordChange] [bit] NULL,
	[bSendEmail] [bit] NULL,
	[bEmailSent] [bit] NULL,
	[bClientApproval] [bit] NULL,
	[vTitle] [varchar](50) NULL,
	[vGoogleEmail] [varchar](200) NULL,
	[vSkypeName] [varchar](200) NULL,
	[vPhoneExtension] [varchar](20) NULL,
	[iComPlanID1] [int] NULL,
	[iComPlanID2] [int] NULL,
	[iComPlanID3] [int] NULL,
	[yAnualThreshold] [money] NULL,
	[vAddress] [varchar](200) NULL,
	[bNotifyOnUploadDocument] [bit] NULL,
	[vLocationIDProduction] [varchar](75) NULL,
	[vLocationIDHarvest] [varchar](75) NULL,
	[bSendJobNotification] [bit] NULL,
 CONSTRAINT [PK_Detail_Employee] PRIMARY KEY CLUSTERED 
(
	[iEmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]