CREATE TABLE [dbo].[webpages_Roles] (
    [RoleId]   INT            IDENTITY (1, 1) NOT NULL,
    [RoleName] NVARCHAR (256) NOT NULL,
    PRIMARY KEY CLUSTERED ([RoleId] ASC) WITH (FILLFACTOR = 80),
    UNIQUE NONCLUSTERED ([RoleName] ASC) WITH (FILLFACTOR = 80),
    UNIQUE NONCLUSTERED ([RoleName] ASC) WITH (FILLFACTOR = 80)
);

