//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEmployeeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Employee
    {
        public int iEmployeeID { get; set; }
        public string vEmployeeName { get; set; }
        public string vEmployeeFunction { get; set; }
        public string cEmployeeStatus { get; set; }
        public string vEmail { get; set; }
        public string vManagerID { get; set; }
        public Nullable<System.DateTime> dHireDate { get; set; }
        public string vNotes { get; set; }
        public bool bAccessFromAnywhere { get; set; }
        public Nullable<int> iSourceID { get; set; }
        public string vEmployeePhone { get; set; }
        public string vEmployeeMobile { get; set; }
        public string vEmployeeFax { get; set; }
        public string vAlternateContactEmail { get; set; }
        public bool bCopyeMailsToAltContact { get; set; }
        public bool bCopyJobeMailsToSourceAltContact { get; set; }
        public bool bIsLandingPage { get; set; }
        public int iFacilityID { get; set; }
        public Nullable<bool> bIsPrimaryGM { get; set; }
        public int iWebUserID { get; set; }
        public Nullable<bool> bRequirePasswordChange { get; set; }
        public Nullable<bool> bSendEmail { get; set; }
        public Nullable<bool> bEmailSent { get; set; }
        public Nullable<bool> bClientApproval { get; set; }
        public string vTitle { get; set; }
        public string vGoogleEmail { get; set; }
        public string vSkypeName { get; set; }
        public string vPhoneExtension { get; set; }
        public Nullable<int> iComPlanID1 { get; set; }
        public Nullable<int> iComPlanID2 { get; set; }
        public Nullable<int> iComPlanID3 { get; set; }
        public Nullable<decimal> yAnualThreshold { get; set; }
        public string vAddress { get; set; }
        public Nullable<bool> bNotifyOnUploadDocument { get; set; }
        public string vLocationIDProduction { get; set; }
        public string vLocationIDHarvest { get; set; }
        public Nullable<bool> bSendJobNotification { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
