//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEmployeeModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class employeeEntities : DbContext
    {
        public employeeEntities()
            : base("name=employeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Detail_Employee> Detail_Employee { get; set; }
    
        [DbFunction("employeeEntities", "GetProductCode")]
        public virtual IQueryable<GetProductCode_Result> GetProductCode(Nullable<int> iPlanID, Nullable<int> manufacturerID, string manufacturerCode, Nullable<int> categoryID, string modelNumber, string functionalStatus, string grade, Nullable<bool> buildAttributes)
        {
            var iPlanIDParameter = iPlanID.HasValue ?
                new ObjectParameter("iPlanID", iPlanID) :
                new ObjectParameter("iPlanID", typeof(int));
    
            var manufacturerIDParameter = manufacturerID.HasValue ?
                new ObjectParameter("ManufacturerID", manufacturerID) :
                new ObjectParameter("ManufacturerID", typeof(int));
    
            var manufacturerCodeParameter = manufacturerCode != null ?
                new ObjectParameter("ManufacturerCode", manufacturerCode) :
                new ObjectParameter("ManufacturerCode", typeof(string));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var modelNumberParameter = modelNumber != null ?
                new ObjectParameter("ModelNumber", modelNumber) :
                new ObjectParameter("ModelNumber", typeof(string));
    
            var functionalStatusParameter = functionalStatus != null ?
                new ObjectParameter("FunctionalStatus", functionalStatus) :
                new ObjectParameter("FunctionalStatus", typeof(string));
    
            var gradeParameter = grade != null ?
                new ObjectParameter("Grade", grade) :
                new ObjectParameter("Grade", typeof(string));
    
            var buildAttributesParameter = buildAttributes.HasValue ?
                new ObjectParameter("BuildAttributes", buildAttributes) :
                new ObjectParameter("BuildAttributes", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProductCode_Result>("[employeeEntities].[GetProductCode](@iPlanID, @ManufacturerID, @ManufacturerCode, @CategoryID, @ModelNumber, @FunctionalStatus, @Grade, @BuildAttributes)", iPlanIDParameter, manufacturerIDParameter, manufacturerCodeParameter, categoryIDParameter, modelNumberParameter, functionalStatusParameter, gradeParameter, buildAttributesParameter);
        }
    
        [DbFunction("employeeEntities", "GetWeekNumberStartEndDate")]
        public virtual IQueryable<GetWeekNumberStartEndDate_Result> GetWeekNumberStartEndDate(string fromdate)
        {
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetWeekNumberStartEndDate_Result>("[employeeEntities].[GetWeekNumberStartEndDate](@fromdate)", fromdateParameter);
        }
    
        [DbFunction("employeeEntities", "SplitString_Custom")]
        public virtual IQueryable<SplitString_Custom_Result> SplitString_Custom(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Custom_Result>("[employeeEntities].[SplitString_Custom](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("employeeEntities", "ufn_CSVToTable")]
        public virtual IQueryable<ufn_CSVToTable_Result> ufn_CSVToTable(string stringInput, string delimiter)
        {
            var stringInputParameter = stringInput != null ?
                new ObjectParameter("StringInput", stringInput) :
                new ObjectParameter("StringInput", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_CSVToTable_Result>("[employeeEntities].[ufn_CSVToTable](@StringInput, @Delimiter)", stringInputParameter, delimiterParameter);
        }
    }
}
