//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEmployee.DatabaseEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLogin
    {
        public int iEmployeeID { get; set; }
        public string vUserName { get; set; }
        public string vPassword { get; set; }
    }
}
